server:
  port: 8083

spring:
  application:
    name: parking-space-service
  datasource:
    url: jdbc:mysql://localhost:3306/spms_parking_space_db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
